---
title: "Presentations"
---
## Talks
-  **Lissón, P.**, Pregla, D., Paape, D., Nicenboim, B., Stadie, N., Burchert., F. & Vasishth, S. (2020). Computational models of retrieval processes in sentence comprehension in aphasia. *26th Architectures and Mechanisms for Language Processing (AMLaP)*, Potsdam, Germany (held online due to COVID-19).

- **Lissón, P.**, Ballier, N. & Gerdes, K. (2019). On relativizer use in French learners of English: a corpus-based study. *5th Learner Corpus Research Conferene (LCR 2019)* Warsaw, Poland.

- Ballier, N. & **Lissón, P.** (2017). A corpus-based evaluation of readability metrics as indices of syntactic complexity in EFL learners’ written productions. *4th Learner Corpus Research Conferene (LCR 2017)*, Bolzano, Italy. [[abstract]](https://www.academia.edu/32530619/A_corpus-based_evaluation_of_readability_metrics_as_indices_of_syntactic_complexity_in_EFL_learners_written_productions_LCR_2017_abstract_)

- Ballier, N. & **Lissón, P.** (2017). Estudio de la aplicabilidad de la ley de Zipf y la ley de Heaps en los corpus de aprendientes de inglés. *International Conference of Corpus Linguistics (CILC 2017)*, France.

## Posters 
- Pregla, D., *Lissón, P.*, Vasishth, S., Burchert., F., Stadie, N. (2020). Sentence comprehension in German speaking individuals with aphasia: A study using varying structures, tasks and test points. *26th Architectures and Mechanisms for Language Processing (AMLaP)*, Potsdam, Germany (held online due to COVID-19).

- *Lissón, P.*, van het Nederend, M., Nicenboim, B., Pregla, D., Paape, D., & Vasishth, S. (2019). Competing models of retrieval in sentence processing: The case of aphasia. To be presented at the *25th Architectures and Mechanisms for Language Processing (AMLaP)*, Moscow, Russia. [[poster]](https://www.dropbox.com/s/ll8ol2t9lw37qjo/amlap_2019.pdf?dl=0)

- **Lissón, P.**, Nicenboim, B., Vasishth, S., & Paape, D. (2019). Models of retrieval in sentence comprehension in aphasia. *StanCon*, Cambridge, UK. [[poster]](https://www.dropbox.com/s/n9wiz3a0otmnjo9/stancon2019.pdf?dl=0)

- **Lissón, P.** & Ballier, N. (2018). Investigating learners’ progression in French as a Foreign Language: vocabulary growth and lexical diversity. *Student Research Day, Ph.D. Program in Speech-Language-Hearing Sciences,* CUNY, NYC.

- **Lissón, P.** & Ballier, N. (2017). Investigating lexical input processing through vocabulary growth curves: a case study of Spanish learners of French L3. *Symposium GDRI-SLAT*, Paris, France.

- Ballier, N., **Lissón, P.** & Trujillo-González, V. (2017). Introducción al uso del paquete {koRpus} de R para el tratamiento de la complejidad léxica y la legibilidad en corpus lingüísticos. *HDH 2017*, Málaga, Spain. [[poster]](https://www.academia.edu/35546181/Introducción_al_uso_del_paquete_koRpus_de_R_para_el_tratamiento_de_la_diversidad_léxica_y_la_legibilidad_en_corpus_lingü%C3%ADsticos)

- **Lissón, P.** & Trujillo-González, V. (2017). A case-study of cross-linguistic transfer in Spanish learners of French L3 as a first step to improve writing skills in French. *International Conference on Multilingualism and Multilingual Education (ICMME17)* Braga, Portugal. 


# Miscellaneous Talks 
1. **Lissón, P.** (2018). Quantitative Methods in SLA: a Short Introduction . *NYU Steinhardt: Second Language: Theory & Research. Spring course*.

2. **Lissón, P.** (2018). On relativizer use in learner English: a corpus-based study. *Vasishth's lab, University of Potsdam*.

3. **Lissón, P.** (2017). A Corpus-based study of lexical diversity and readability in EFL learners’ productions: towards a critical statistical approach. *Journée de Recherche M2, Paris Diderot*.


