---
title: "Publications"
---
## Preprints
Pregla, D., **Lissón**, P., Vasishth, S., Burchert, F., & Stadie, N. (2020, September 18). Variability in sentence comprehension in aphasia in German. https://doi.org/10.31234/osf.io/7hfpx

## In peer-reviewed journals
- **Lissón, P.**, Pregla, D., Nicenboim, B., Paape, D., van het Nederend, M. L., Burchert, F., Stadie, N., Caplan, D.,  Vasishth, S. (in press). A computational evaluation of two models of retrieval processes in sentence processing in aphasia. *Cognitive Science*. [[arXiv]](https://doi.org/10.31234/osf.io/r7dn5)

- Arnold, T., Ballier, N., **Lissón, P.**, & Tilton, L. (2019). Beyond Lexical Frequencies: Using R for Text Analysis in the Digital Humanities. *Language Resources and Evaluation, 53(4), 707-733.* [[link]](https://doi.org/10.1007/s10579-019-09456-6) [[author version]](https://statsmaths.github.io/pdf/2018-beyond-lex.pdf)

- **Lissón P.**, & Ballier, N. (2018). Investigating lexical progression through lexical diversity metrics in a Corpus of French L3. *Discours. Revue de linguistique, psycholinguistique et informatique. A journal of linguistics, psycholinguistics and computational linguistics, (23).* [[link]](https://journals.openedition.org/discours/9950)

- **Lissón P.** & Trujillo-González, V. (2018). Détection des transferts interlangues chez des apprenants universitaires de français troisième langue. *Synergies Espagne 11, 55-70*. [[link]](http://gerflint.fr/Base/Espagne11/lisson_trujillo.pdf)

<!-- 4. **Lissón P.** (2017). Investigating the use of readability metrics to detect differences in written productions of -->
<!-- learners: a corpus-based study. *Bellaterra Journal of Teaching & Learning Language & Literature , 10 (4), 68-86.* DOI: [10.5565/rev/jtl3.752](https://doi.org/10.5565/rev/jtl3.752) -->

## In peer-reviewed proceedings 
1. Ballier, N., Gaillat, T., Arnold, T.,**Lissón P.** (2018). Predicting CEFRL levels in learner English on the basis of metrics and full texts. *Conférence sur l'Apprentissage Automatique (CAP 2018), Rouen, France*. [[link]](https://arxiv.org/abs/1806.11099)

2. Ballier, N. & **Lissón P.** (2017). R-based strategies for DH in English Linguistics: a case study. Teaching NLP for Digital Humanities, *workshop of the German Society for Computational Linguistics conference (GSCL 2017)*.In P. Bockwinkel, T. Declerck, S. Kübler, & H. Zinsmeister (Eds.), Proceedings of the Workshop on Teaching NLP for Digital Humanities (Vol. 1918, pp. 1–10). Berlin, Germany: CEUR Workshop Proceedings. [[link]](<http://ceur-ws.org/Vol-1918/ballier.pdf>)


